<?php

namespace MaaximOne\LaAdmin\Classes\Page;

class FileField extends Field
{
    public ?string $_path = null;
    public ?string $_public_path = null;
    public bool $_multiple = true;
    public string $_accept = "*";

    /**
     * @param string|null $path
     * @return FileField
     */
    public function setPath(?string $path): FileField
    {
        $this->_path = $path;
        return $this;
    }

    /**
     * @param string|null $public_path
     * @return FileField
     */
    public function setPublicPath(?string $public_path): FileField
    {
        $this->_public_path = $public_path;
        return $this;
    }

    /**
     * @param bool $multiple
     * @return FileField
     */
    public function setMultiple(bool $multiple): FileField
    {
        $this->_multiple = $multiple;
        return $this;
    }

    /**
     * @param string $accept
     * @return FileField
     */
    public function setAccept(string $accept): FileField
    {
        $this->_accept = $accept;
        return $this;
    }

    public function __toResponse(): object
    {
        $data = parent::__toResponse();
        $data->multiple = $this->_multiple;
        $data->accept = $this->_accept;

        return $data; // TODO: Change the autogenerated stub
    }
}
